hospital_management_system/routes/web.php
<?php

use App\Http\Controllers\HospitalController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/staff_register', 'StaffRegisterController@index')->name('staff_register'); 
Route::post('/staff_register/store', 'StaffRegisterController@store')->name('staff_register.store');

Route::middleware(['auth'])->group(function(){ //, 'verifyuser'

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('user', 'UsersController');
    Route::resource('hospital', 'HospitalController');
    Route::put('/hospital/{hospital}', 'HospitalController@show')->name('hospital.show');
    Route::put('/hospital/{hospital}/book', 'HospitalController@bookABed')->name('hospital_beds.book');
    Route::get('/booking', 'BookingController@index')->name('booking.index');

    Route::put('/hospital/booking/{booking}', 'UserBookingsController@destroy')->name('user_booking.destroy');

    Route::get('/discharge', 'DischargeController@index')->name('discharge.index');
    Route::put('/discharge/remove/{user_id}', 'UserBookingsController@destroyPermanent')->name('user_booking.remove');
    
    Route::get('/clear', 'HospitalController@clearNotification')->name('notification.clear');
});

hospital_management_system/resources/views/layouts/components/_message.blade.php
<div class="container">
<div class="row">
    <div class="col-md-12">
        @if(session()->has('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{session()->get('success')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        @if(session()->has('error'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{session()->get('error')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
    </div>
</div>
</div>

hospital_management_system/resources/views/layouts/components/_navbar.blade.php
<div class="col-md-12 p-0" style="z-index:1;">
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm p-0">
            <div class="container-fluid">
                <a class="navbar-brand px-5 my-2" href="{{ url('/') }}">
                <span class="color-main">  <strong>{{ config('app.name', 'Covid') }}</strong></span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
</div>

hospital_management_system/resources/views/layouts/components/_sidebar.blade.php
<div class="col-md-2" id="sidebar">
    <div class="logo-area">
        @if(auth()->user()->isStaff())
            <div class="btn main-purple-back color-white booking-btn py-2 px-3">View Bookings
            <span class="badge badge-pill" style=" background-color: #fff!important;color:#713BDB;">{{ App\User_bookings::all_booking_number() }}  </span>
            </div>
        @endif
    </div>
    <div class="div mt-5">
        <ul>

            @if(auth()->user()->isUser())
            <!-- dd(URL::current()) -->
                <li class="@yield('active_home')"><a href="{{ route('user.index') }}">
                    <span class="fas fa-home hover-purple"></span>&nbsp; <span class="hover-black">Home</span></a>
                </li>
                <li class="@yield('active_bookings')">
                    <a href="{{ route('booking.index') }}">
                        <span class="fas fa-bed hover-purple"></span>&nbsp; <span class="hover-black">Bookings</span>
                        <span class="badge badge-pill" style=" background-color: #713BDB!important;color:#fff;">{{ App\User::booking_number() }}  </span>
                    </a>
                </li>
            @endif

            @if(auth()->user()->isStaff())
                <li class="@yield('active_home')"><a href="{{ route('hospital.index') }}"><span class="fas fa-home hover-purple"></span>&nbsp; <span class="hover-black">Home</span></a></li>
                <li  class="@yield('active_bookings')">
                    <a href="{{ route('booking.index') }}">
                        <span class="fas fa-bed hover-purple"></span>&nbsp; <span class="hover-black">Bookings</span>
                        <span class="badge badge-pill" style=" background-color: #713BDB!important;color:#fff;">{{ App\User_bookings::all_booking_number() }}  </span>
                    </a>
                </li>
                <li class="@yield('active_discharge')"><a href="{{ route('discharge.index') }}"><span class="fas fa-clipboard-list hover-purple"></span>&nbsp; <span class="hover-black">Discharge List</span></a></li>
            @endif

        </ul>
    </div>
</div>

@section('page-level-styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
@endsection

@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js"></script>
@endsection

hospital_management_system/resources/views/layouts/components/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@yield('title')</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="utf-8">
    <meta name="author" content="John Doe">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css" integrity="sha512-/zs32ZEJh+/EO2N1b0PEdoA10JkdC3zJ8L5FTiQu82LR9S/rOQNfQN7U59U9BC12swNeRAz3HSzIL2vpp4fv3w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    @yield('page-level-styles')

</head>
<body>
    <div class="">
        @include('layouts.components._navbar')
        <div class="container-fluid">
            <div class="row">
                
                 @include('layouts.components._sidebar')

                <div class="col-md-10 pt-4" style="max-width: 100%!important;">
                    @include('layouts.components._message')
                    @yield('main-content')
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/fontawesome.min.js" integrity="sha512-kI12xOdWTh/nL2vIx5Yf3z/kJSmY+nvdTXP2ARhepM/YGcmo/lmRGRttI3Da8FXLDw0Y9hRAyZ5JFO3NrCvvXA==" crossorigin="anonymous"></script>
    @yield('page-level-scripts')

</body>
</html>